### ISSUE TITLE
Durante instalação mensagem "Option 'extensions-dir' is defined more than once"

### ISSUE THREAD

**Issue by bcribas** [maratona-linux/maratona-team-tools#22]
```Option 'extensions-dir' is defined more than once. Using value '/opt/vscode-extensions/.'
Option 'extensions-dir' is defined more than once. Using value '/opt/vscode-extensions/.'
Option 'extensions-dir' is defined more than once. Using value '/opt/vscode-extensions/.'
Option 'extensions-dir' is defined more than once. Using value '/opt/vscode-extensions/.'
```

Isso parece um erro (ou um warning) com algum parâmetro.

**Comment by gdeusdara** [comment]
Isso é porque o comando vscode do flatpak é modificado previamente para usar o extensions-dir no comando padrão dele, ai quando uso para mudar para a pasta /opt/vscode-extensions/ ele dá esse warning.

**Comment by DaviAntonio** [comment]
Desde o commit maratona-linux/maratona-team-tools@bfc6e2f5b083d3207b477cfe520812c302423baa não se usa mais Flatpak para se instalar o VSCode no Maratona Linux.
